### ISSUE TITLE
Incorrectly formats XML files with DOCTYPE statements

### ISSUE THREAD

**Issue by hinchliff** [revelc/xml-formatter#7]
See RENCI-NRIG/orca5#176

[Example diff](https://github.com/RENCI-NRIG/orca5/commit/0ff070ee9df1293f74b9f16e26f2b33f0f38a71e#diff-6d0ca63a6a8548b23def2bbe58b2cbfd)
``` 
-<!DOCTYPE project [
-<!ENTITY deps SYSTEM “ant/deps.xml”>
-<!ENTITY core SYSTEM “ant/core.xml”>
-<!ENTITY packages SYSTEM “ant/packages.xml”>
-<!ENTITY tests SYSTEM “ant/tests.xml”>
-]>

+<!DOCTYPE project> 
+<!--ENTITY core SYSTEM “ant/core.xml”--> 
+<!--ENTITY packages SYSTEM “ant/packages.xml”--> 
+<!--ENTITY tests SYSTEM “ant/tests.xml”-->
+ ]&gt;
```

**Comment by hinchliff** [comment]
I'm not involved with that project anymore, but I took a quick look anyway.

First, it's not immediately obvious how I start using this new xml-formatter project.  Do I just need to use the latest version of the `formatter-maven-plugin` plugin?

Unfortunately that resulted in some SAXParserException on this (orca5) project:
> [ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.9.0:format (default-cli) on project orca: Execution default-cli of goal net.revelc.code.formatter:formatter-maven-plugin:2.9.0:format failed: org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 2; The markup in the document following the root element must be well-formed. -> [Help 1]


The error message doesn't tell you which file caused the error, but turning on maven debugging (`-X`) seems to indicate that it was processing [orca5/blob/master/boot/ant/deps.xml](https://github.com/RENCI-NRIG/orca5/blob/master/boot/ant/deps.xml), although I don't see any obvious errors in that file.

**Comment by ctubbsii** [comment]
> First, it's not immediately obvious how I start using this new xml-formatter project. Do I just need to use the latest version of the `formatter-maven-plugin` plugin?

Using the latest `formatter-maven-plugin` is probably the most common way to use it. However, you could also create an instance of `new XmlDocumentFormatter(...).format(...)` to use it directly in your code.

**Comment by jam01** [comment]
The XML formatter uses a SAXParser to validate the XML is good before trying to format it. Not sure about the error pointing to line 9 column 2, but [boot/ant/deps.xml](https://github.com/RENCI-NRIG/orca5/blob/master/boot/ant/deps.xml) seems to be line invalid XML since it does not have a root element. So that's very interesting and not sure how we would deal with this or if we should.

**Comment by ctubbsii** [comment]
There's a similar problem in `impsort-maven-plugin`, where it fails to sort imports if the Java code isn't valid. So far, I've chosen to not fix the problem... and just tell people that valid Java is a prerequisite.

However, for XML, I think it might be a common thing for config files to be "snippets" of XML, rather than full XML. I think the question here is whether this formatter should also format such snippets. If so, maybe it can try to catch the exception, wrap with a dummy root element, re-try to format, and then strip out the dummy root element that was inserted?

**Comment by hinchliff** [comment]
Having the plugin fail with an error may not be the best solution, when previous versions of the plugin would run to completion without even a warning.

It might be reasonable to catch the exception and print a warning before skipping the file.

It's not clear to me what if anything previous versions (2.6.0) of the plugin did or attempted to do for this file, all the debug log says is:
> Nothing formatted. Try to fix line endings.

**Comment by jam01** [comment]
Interestingly enough as I understand it this is a valid Ant configuration file (never dealt with Ant before), and the original formatter was for Ant. So it's worth noting that I introduced the SAXParser when refactoring code, without that well formed check the file is processed fine.

So while the original implementation does not check for valid XML it does suppress any errors and just copies tags as-is, [see here](https://github.com/revelc/xml-formatter/blob/master/src/main/java/net/revelc/code/formatter/xml/lib/XMLTagFormatter.java#L37). I suppose this is fine and probably a desired over failure, only downside being that it would not serve a developer to catch invalid XMLs whereas for example malformed Java would be caught in compilation, but that's more along the lines of the default XML formatter in Eclipse anyway.

So all in all I'm OK with removing the SAX validation if you guys agree.

**Comment by ctubbsii** [comment]
Could make the SAX validation optional, with different modes: "FAIL, WARN, IGNORE"
